# Generated by Django 3.0.5 on 2020-04-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
